export const COURSES = [
  { id: "crochet-start", name: "Crochet beginnings", craft: "crocheting", lessons: ["foundation-chain", "single-crochet", "slip-stitch-crochet", "half-double-crochet", "double-crochet"], question: "How many loops remain on the hook after a completed single crochet?", answers: ["One", "Two", "Three"], correct: 0 },
  { id: "knit-start", name: "Knitting beginnings", craft: "knitting", lessons: ["cast-on", "knit", "garter", "purl", "bind-off"], question: "Where is the working yarn when you make a knit stitch?", answers: ["Behind the work", "In front of the work", "Over both needles"], correct: 0 },
  { id: "cross-start", name: "Cross stitch beginnings", craft: "cross-stitch", lessons: ["x-fabric-count", "x-loop-start", "x-full-cross", "x-ending-thread"], question: "How should the top legs of your cross stitches face?", answers: ["All in the same direction", "Alternate every stitch", "Any direction"], correct: 0 },
] as const;

export interface LessonCheck { question: string; answers: string[]; correct: number; practice: string; }
export const LESSON_CHECKS: Record<string, LessonCheck> = {
  "foundation-chain": { question: "Does the loop on your hook count as a chain?", answers: ["No", "Yes", "Only on the first row"], correct: 0, practice: "Make 11 chains. Count the V shapes below your hook; leave the active loop out of the count." },
  "single-crochet": { question: "How many loops do you pull through to finish single crochet?", answers: ["One", "Two", "Three"], correct: 1, practice: "Chain 11. Start in the second chain from the hook and work 10 single crochet. Chain one, turn, and work 10 more." },
  "slip-stitch-crochet": { question: "After pulling up the new loop, what completes a slip stitch?", answers: ["Yarn over twice", "Chain one", "Pull it through the existing hook loop"], correct: 2, practice: "Make a short chain, then slip stitch into each chain without tightening the loops excessively." },
  "half-double-crochet": { question: "How many loops are on the hook before the final pull-through?", answers: ["Three", "Two", "Four"], correct: 0, practice: "Work a row of 10 half double crochet stitches. Check that you yarn over before inserting the hook." },
  "double-crochet": { question: "How do you finish a US double crochet after pulling up a loop?", answers: ["Pull through all loops at once", "Pull through two loops, then through two again", "Make a slip stitch"], correct: 1, practice: "Work a row of US double crochet. Decide whether your turning chain counts as a stitch and keep that convention for the swatch." },
  "cast-on": { question: "Where should you count your cast-on loops?", answers: ["Along the yarn tail", "Only below the needle", "On the needle, including the initial slip knot"], correct: 2, practice: "Cast on 12 stitches. Check that each loop can slide along the needle shaft." },
  "knit": { question: "Where is the working yarn for a knit stitch?", answers: ["Behind the work", "In front", "Around both needle tips"], correct: 0, practice: "Knit all 12 stitches. Count again before turning the work." },
  "garter": { question: "How do you make garter stitch when working flat?", answers: ["Alternate knit and purl rows", "Knit every row", "Knit one, purl one across each row"], correct: 1, practice: "Knit six rows. Look for three ridges and count the live stitches." },
  "purl": { question: "Where is the working yarn for a purl stitch?", answers: ["Behind the work", "On the floor", "In front of the work"], correct: 2, practice: "Purl 12 stitches, keeping the yarn in front. Alternate a knit row and a purl row to compare the two faces." },
  "bind-off": { question: "Which loop passes over the other in a basic bind-off?", answers: ["The older loop passes over the newer loop", "The newer loop passes over the older loop", "Both loops are dropped together"], correct: 0, practice: "Bind off your swatch loosely. Check that its top edge stretches about as much as the fabric below." },
  "x-fabric-count": { question: "What does 14-count Aida mean?", answers: ["Use 14 strands of floss", "There are 14 stitch squares per inch", "Make 14 stitches per design"], correct: 1, practice: "Measure one inch of Aida and count the squares across it." },
  "x-loop-start": { question: "What secures a loop start?", answers: ["A knot on the front", "Glue", "Passing the needle through the folded thread loop at the back"], correct: 2, practice: "Fold one strand in half and practise securing it through the loop on the reverse." },
  "x-full-cross": { question: "Which direction should the top legs face?", answers: ["The same direction throughout", "Alternate every stitch", "Any direction"], correct: 0, practice: "Work a row of five crosses with all top legs facing the same direction." },
  "x-ending-thread": { question: "How can you finish the thread neatly?", answers: ["Cut it flush against the last stitch", "Weave it beneath several stitches on the back", "Leave a long loose loop"], correct: 1, practice: "Slide the needle under several stitches on the reverse without piercing the front, then trim." },
};
